### ISSUE TITLE
All scale is showing as 0

### ISSUE THREAD

**Issue by Prashanthlkv** [CodeAndMagic/GaugeView#10]
I am running the your code in LG Nexus(Loolipop) and all the scales is showing as zero(0) instead of 0,10,20,30,40,50,60,70,80,90,100. Please help me in resolving this.Thanks in advance

**Comment by Sulejman** [comment]
It seems that on versions after 4.2 method canvas.drawText() is not working properly. Here is the link with description of the problem: http://stackoverflow.com/questions/13941270/android-4-2-on-nexus-7-canvas-drawtext-not-working-correctly

But the thing is that still it doesn't work, since in Lollipop this method paint.setLinearText(true) is deprecated.  The thing is, numbers will show correctly if you set paint.setTextSize(1f) but in that case you must revise the scale of everything else. It seems that this is only solution that will work for us. I still didn't figured out exactly how I will do it, but I'm desperate and will have to write new gauge at the end of the day. Please help.

**Comment by Sulejman** [comment]
I fixed this thing, if anyone is interested contact me sulejmansarajlija@gmail.com, I'll also fork it later.

**Comment by miguelbelem** [comment]
I'm having the same problem. Some help?

**Comment by Sulejman** [comment]
Instead of using canvas.draw method directly with text size less than 1.0f: 

```java
canvas.drawText(valueString(value), 0.49f, y3 + 0.05f, paint);
```

I used this workaround method:

```java
private void drawText(Canvas canvas, String value, float x, float y, float size, Paint paint)
    {
        //Save original font size
        float originalTextSize = paint.getTextSize();

        // set a magnification factor
        final float magnifier = 100f;

        // Scale the canvas
        canvas.save();
        canvas.scale(1f / magnifier, 1f / magnifier);

        // increase the font size
        paint.setTextSize(originalTextSize * magnifier);

        canvas.drawText(value, x*magnifier, y*magnifier,paint);

        //canvas.drawTextOnPath(value, textPath, 0.0f, 0.0f, paint);

        // bring everything back to normal
        canvas.restore();
        paint.setTextSize(originalTextSize);
    }
```

**Comment by ssaurel** [comment]
Hello,

Your solution still not work on Android 5.x .Nothing is displayed.

Sylvain

**Comment by Sulejman** [comment]
That is very poor information for me to help you. Could you provide detail explanation?

**Comment by ssaurel** [comment]
Thanks for your reply.

I copied your workaround method and use it in the drawScale method of GaugeView class.

Call is like that in the project : 

canvas.drawText(valueString(mScaleStartValue + value), 0.5f,  y3 + 0.045f, paint);


I changed to use with your workaround method like that : 

drawText(canvas, valueString(mScaleStartValue + value), 0.5f,  y3 + 0.045f, 1f, paint);


Note that the size parameter is never used in your workaround method.

For me, on Android 5.0.1 no text is displayed.

Did you make any other changes ?

**Comment by Sulejman** [comment]
I’m using much smaller text size: 

	drawText(canvas, valueString(value), 0.5f, y3 + 0.05f, 0.03f, paint);

The point of this method is to zoom out the canvas, draw text of size greater than 1f and then make it all smaller without losing text. Try using 0.03f as a text size. Works for me.

**Comment by Sulejman** [comment]
Let me know if that works.

**Comment by ssaurel** [comment]
I guess I haven't the good version of you drawText workaround method because size parameter is never used in the version you posted on github comment.

So, it has no effect to change value.

**Comment by Sulejman** [comment]
Yes, you do, it’s the one from git issue section, 

drawText(Canvas canvas, String value, float x, float y, float size, Paint paint)

Notice the size in parameters, you are using it like this:

drawText(canvas, valueString(mScaleStartValue + value), 0.5f, y3 + 0.045f, 1f, paint);

and I’m using it like this:

drawText(canvas, valueString(value), 0.5f, y3 + 0.05f, 0.03f, paint);

**Comment by ssaurel** [comment]
In the git issue section code is like that : 

	private void drawText(Canvas canvas, String value, float x, float y,
			float size, Paint paint) {
		// Save original font size
		float originalTextSize = paint.getTextSize();

		// set a magnification factor
		final float magnifier = 100f;

		// Scale the canvas
		canvas.save();
		canvas.scale(1f / magnifier, 1f / magnifier);

		// increase the font size
		paint.setTextSize(originalTextSize * magnifier);

		canvas.drawText(value, x * magnifier, y * magnifier, paint);

		// canvas.drawTextOnPath(value, textPath, 0.0f, 0.0f, paint);

		// bring everything back to normal
		canvas.restore();
		paint.setTextSize(originalTextSize);
	}


but size variable is never used in your code. So, change value won't have any impact.

**Comment by Sulejman** [comment]
Sorry, my bad, can you add me on skype to solve this faster? sulejman_sarajlija

**Comment by ssaurel** [comment]
I have no skype but we can exchange thanks to gmail if you want : sylvain.saurel@gmail.com

**Comment by miguelbelem** [comment]
If you solve the problem please say your conclusions here. Tks

**Comment by Sulejman** [comment]
If nothing is displayed as you are saying, than something else is the problem, not the canvas.drawText.
This is the screen without workaround method:

![screen shot 2015-04-11 at 15 21 42](https://cloud.githubusercontent.com/assets/3107367/7101550/b4ccdd12-e05e-11e4-990b-9d3c63ab0dde.png)

and this is with that method:

![screen shot 2015-04-11 at 15 22 26](https://cloud.githubusercontent.com/assets/3107367/7101551/c1880e64-e05e-11e4-9ef9-a4685805dfd6.png)

If no text is being displayed, I think you might be having some other issue and not the one described in here.

**Comment by ssaurel** [comment]
After viewed your screenshots, i think it's changes from your side that solves the problem. 

Try to apply your method with code  on the github repo and you will  see the problem

**Comment by Sulejman** [comment]
Look, I forked this project and will update my changes in my repository in few hours and paste link here. Then try my version of code and see how it works.

**Comment by Sulejman** [comment]
Here's a complete tutorial for this gauge view which is updated and works for android:

http://www.sule.io/?p=25

**Comment by raghu1082** [comment]
Hi Sulejman, thanks for the code, kindly tell me how can i set the needle to the value say 30 or 40 or some other value. here the needle is rotating every second based on the timer method in the activity file. i want to pass values like 10 or 20 or 30 and so on and want the needle to point to that location. Kindly help me on this.

**Comment by Sulejman** [comment]
Please post that question here in the comment section:
